image: maven:latest

variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:
        - .m2/repository/
        - target/

build:
    stage: build
    script:
        - mvn compile
    tag:
        - tu-tag


test:
    stage: test
    script:
        - mvn  test
    tag:
        - tu-tag

deploy:
    stage: deploy
    script:
        - mvn package
    only:
        - master
    tag:
        - tu-tag
    artifacts:
        paths:
            - target/fiaeTest-1.0-SNAPSHOT.jar
