image: maven:latest

variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:
        - .m2/repository/
        - target/

build:
    stage: build
    script:
        - mvn compile
    tags: 
        - myrunner


test:
    stage: test
    script:
        - mvn  test
    tags: 
        - myrunner

deploy:
    stage: deploy
    script:
        - mvn package
    tags: 
        - myrunner
    only:
        - master
    artifacts:
        paths:
            - target/ticketautomat_schueler-1.0-SNAPSHOT.jar
