/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiaeTest.gui;

import java.util.ArrayList;

import fiaeTest.Coin;
import fiaeTest.Coins;
import fiaeTest.ECCard;
import fiaeTest.Payment;
import fiaeTest.States;
import fiaeTest.Ticket;
import fiaeTest.Ticketautomat;
import fiaeTest.TicketautomatListener;
import fiaeTest.Zonen;

/**
 *
 * @author Jörg
 */
public class MainFrame extends javax.swing.JFrame implements TicketautomatListener {

    private Ticketautomat ticketautomat;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ct1Button = new javax.swing.JButton();
        summeLabel = new javax.swing.JLabel();
        preisLabel = new javax.swing.JLabel();
        ct2Button = new javax.swing.JButton();
        ct5Button = new javax.swing.JButton();
        ct10Button = new javax.swing.JButton();
        ct20Button = new javax.swing.JButton();
        ct50Button = new javax.swing.JButton();
        eur1Button = new javax.swing.JButton();
        eur2Button = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        ecRadioButton = new javax.swing.JRadioButton();
        pinTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        barRadioButton = new javax.swing.JRadioButton();
        zone1ToggleButton = new javax.swing.JToggleButton();
        zone3ToggleButton = new javax.swing.JToggleButton();
        zone2ToggleButton = new javax.swing.JToggleButton();
        falschgeldCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket Automat");
        setName("Ticketautomat"); // NOI18N
        setResizable(false);

        ct1Button.setText("1ct");
        ct1Button.setEnabled(false);
        ct1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct1ButtonActionPerformed(evt);
            }
        });

        summeLabel.setBackground(new java.awt.Color(0, 153, 153));
        summeLabel.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        summeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        summeLabel.setText("0.00 EUR");

        preisLabel.setBackground(new java.awt.Color(0, 153, 153));
        preisLabel.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        preisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preisLabel.setText("0.00 EUR");

        ct2Button.setText("2ct");
        ct2Button.setEnabled(false);
        ct2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct2ButtonActionPerformed(evt);
            }
        });

        ct5Button.setText("5ct");
        ct5Button.setEnabled(false);
        ct5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct5ButtonActionPerformed(evt);
            }
        });

        ct10Button.setText("10ct");
        ct10Button.setEnabled(false);
        ct10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct10ButtonActionPerformed(evt);
            }
        });

        ct20Button.setText("20ct");
        ct20Button.setEnabled(false);
        ct20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct20ButtonActionPerformed(evt);
            }
        });

        ct50Button.setText("50ct");
        ct50Button.setEnabled(false);
        ct50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct50ButtonActionPerformed(evt);
            }
        });

        eur1Button.setText("1€");
        eur1Button.setEnabled(false);
        eur1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eur1ButtonActionPerformed(evt);
            }
        });

        eur2Button.setText("2€");
        eur2Button.setEnabled(false);
        eur2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eur2ButtonActionPerformed(evt);
            }
        });

        cButton.setBackground(new java.awt.Color(255, 0, 0));
        cButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(ecRadioButton);
        ecRadioButton.setText("EC-Karte");
        ecRadioButton.setEnabled(false);
        ecRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecRadioButtonActionPerformed(evt);
            }
        });

        pinTextField.setText("1234");
        pinTextField.setEnabled(false);
        pinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("PIN:");

        buttonGroup1.add(barRadioButton);
        barRadioButton.setText("Bar");
        barRadioButton.setEnabled(false);
        barRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barRadioButtonActionPerformed(evt);
            }
        });

        zone1ToggleButton.setText("Zone 1");
        zone1ToggleButton.setEnabled(false);
        zone1ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zone1ToggleButtonActionPerformed(evt);
            }
        });

        zone3ToggleButton.setText("Zone 3");
        zone3ToggleButton.setEnabled(false);
        zone3ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zone3ToggleButtonActionPerformed(evt);
            }
        });

        zone2ToggleButton.setText("Zone 2");
        zone2ToggleButton.setEnabled(false);
        zone2ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zone2ToggleButtonActionPerformed(evt);
            }
        });

        falschgeldCheckBox.setText("Falschgeld");

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        logTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logTextAreaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(logTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zone1ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cButton))
                            .addComponent(zone3ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zone2ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(summeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ecRadioButton)
                                    .addComponent(barRadioButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(ct1Button))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pinTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ct2Button)
                                        .addGap(12, 12, 12)
                                        .addComponent(ct5Button)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct10Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct20Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct50Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eur1Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eur2Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(falschgeldCheckBox)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cButton)
                            .addComponent(zone1ToggleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zone2ToggleButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(summeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zone3ToggleButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct1Button)
                    .addComponent(ct2Button)
                    .addComponent(ct5Button)
                    .addComponent(ct10Button)
                    .addComponent(ct20Button)
                    .addComponent(ct50Button)
                    .addComponent(eur1Button)
                    .addComponent(eur2Button)
                    .addComponent(barRadioButton)
                    .addComponent(falschgeldCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ecRadioButton)
                    .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zone3ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zone3ToggleButtonActionPerformed
        ticketautomat.select(Zonen.Zone3);
        zone1ToggleButton.setSelected(false);
        zone2ToggleButton.setSelected(false);
    }//GEN-LAST:event_zone3ToggleButtonActionPerformed

    private void zone1ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zone1ToggleButtonActionPerformed
        ticketautomat.select(Zonen.Zone1);
        zone2ToggleButton.setSelected(false);
        zone3ToggleButton.setSelected(false);
    }//GEN-LAST:event_zone1ToggleButtonActionPerformed

    private void zone2ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zone2ToggleButtonActionPerformed
        ticketautomat.select(Zonen.Zone2);
        zone1ToggleButton.setSelected(false);
        zone3ToggleButton.setSelected(false);
    }//GEN-LAST:event_zone2ToggleButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        ticketautomat.reset();
    }//GEN-LAST:event_cButtonActionPerformed

    private void barRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barRadioButtonActionPerformed
        ticketautomat.setPayment(Payment.BAR);
    }//GEN-LAST:event_barRadioButtonActionPerformed

    private void ecRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecRadioButtonActionPerformed
        ticketautomat.setPayment(Payment.ECCARD);
    }//GEN-LAST:event_ecRadioButtonActionPerformed

    private void ct1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct1ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.CT1,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_ct1ButtonActionPerformed

    private void ct2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct2ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.CT2,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_ct2ButtonActionPerformed

    private void ct5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct5ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.CT5,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_ct5ButtonActionPerformed

    private void ct10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct10ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.CT10,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_ct10ButtonActionPerformed

    private void ct20ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct20ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.CT20,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_ct20ButtonActionPerformed

    private void ct50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct50ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.CT50,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_ct50ButtonActionPerformed

    private void eur1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eur1ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.EUR1,falschgeldCheckBox.isSelected()));
    }//GEN-LAST:event_eur1ButtonActionPerformed

    private void eur2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eur2ButtonActionPerformed
        ticketautomat.addCoin(new Coin(Coins.EUR2,falschgeldCheckBox.isSelected()));

    }//GEN-LAST:event_eur2ButtonActionPerformed

    private void pinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTextFieldActionPerformed
       
        ticketautomat.insertEcCard(new ECCard(pinTextField.getText()));
    }//GEN-LAST:event_pinTextFieldActionPerformed

    private void logTextAreaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logTextAreaMouseEntered
       
            logTextArea.setText("");
    }//GEN-LAST:event_logTextAreaMouseEntered

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton barRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cButton;
    private javax.swing.JButton ct10Button;
    private javax.swing.JButton ct1Button;
    private javax.swing.JButton ct20Button;
    private javax.swing.JButton ct2Button;
    private javax.swing.JButton ct50Button;
    private javax.swing.JButton ct5Button;
    private javax.swing.JRadioButton ecRadioButton;
    private javax.swing.JButton eur1Button;
    private javax.swing.JButton eur2Button;
    private javax.swing.JCheckBox falschgeldCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JTextField pinTextField;
    private javax.swing.JLabel preisLabel;
    private javax.swing.JLabel summeLabel;
    private javax.swing.JToggleButton zone1ToggleButton;
    private javax.swing.JToggleButton zone2ToggleButton;
    private javax.swing.JToggleButton zone3ToggleButton;
    // End of variables declaration//GEN-END:variables

    public void setAutomat(Ticketautomat ticketautomat) {
        this.ticketautomat = ticketautomat;
    }

    @Override
    public void setState(States s) {
        switch (s) {

            case PAY_BAR:
                ct1Button.setEnabled(true);
                ct2Button.setEnabled(true);
                ct5Button.setEnabled(true);
                ct10Button.setEnabled(true);
                ct20Button.setEnabled(true);
                ct50Button.setEnabled(true);
                eur1Button.setEnabled(true);
                eur2Button.setEnabled(true);
                ecRadioButton.setEnabled(false);
                barRadioButton.setEnabled(false);
                break;
            case PAY_EC:
                pinTextField.setEnabled(true);
                logTextArea.append("** Karte eingeführt, PIN eingeben**\n");
                ecRadioButton.setEnabled(false);
                barRadioButton.setEnabled(false);
                break;
            case SELECT_PAYMENT:
                zone1ToggleButton.setEnabled(false);
                zone2ToggleButton.setEnabled(false);
                zone3ToggleButton.setEnabled(false);
                barRadioButton.setEnabled(true);
                ecRadioButton.setEnabled(true);
                break;
            case SELECT_ZONE:
                zone1ToggleButton.setEnabled(true);
                zone2ToggleButton.setEnabled(true);
                zone3ToggleButton.setEnabled(true);
                zone1ToggleButton.setSelected(false);
                zone2ToggleButton.setSelected(false);
                zone3ToggleButton.setSelected(false);
                barRadioButton.setEnabled(false);
                ecRadioButton.setEnabled(false);
                ecRadioButton.setSelected(false);
                barRadioButton.setEnabled(false);
                ecRadioButton.setEnabled(false);
                buttonGroup1.clearSelection();
                pinTextField.setEnabled(false);
                preisLabel.setText("0.00 EUR");
                ct1Button.setEnabled(false);
                ct2Button.setEnabled(false);
                ct5Button.setEnabled(false);
                ct10Button.setEnabled(false);
                ct20Button.setEnabled(false);
                ct50Button.setEnabled(false);
                eur1Button.setEnabled(false);
                eur2Button.setEnabled(false);
                break;

        }
    }

    @Override
    public void dispayPrice(Ticket t) {
        preisLabel.setText(t.getPreis() + " EUR");
    }

    @Override
    public void reset() {
        logTextArea.setEditable(false);
        zone1ToggleButton.setSelected(false);
        zone2ToggleButton.setSelected(false);
        zone3ToggleButton.setSelected(false);
        zone1ToggleButton.setEnabled(false);
        zone2ToggleButton.setEnabled(false);
        zone3ToggleButton.setEnabled(false);
        barRadioButton.setSelected(false);
        ecRadioButton.setSelected(false);
        barRadioButton.setEnabled(false);
        ecRadioButton.setEnabled(false);
        buttonGroup1.clearSelection();
        preisLabel.setText("0.00 EUR");
        ct1Button.setEnabled(false);
        ct2Button.setEnabled(false);
        ct5Button.setEnabled(false);
        ct10Button.setEnabled(false);
        ct20Button.setEnabled(false);
        ct50Button.setEnabled(false);
        eur1Button.setEnabled(false);
        eur2Button.setEnabled(false);
        pinTextField.setEnabled(false);
        
        setState(States.SELECT_ZONE);
    }

    @Override
    public void dispaySum(double sum) {
        summeLabel.setText(Double.toString(sum) + " EUR");
    }

    @Override
    public void returnCoins(ArrayList<Coin> c) {
        logTextArea.append("\n** Geldauswurf **\n");
        for (Coin coin: c) {
            logTextArea.append(coin.toString());
        }
    }

    @Override
    public void returnTicket(String s) {
        logTextArea.append("\n** Ticket entnehmen **\n");
        logTextArea.append(s);
    }

    @Override
    public void returnECCard(ECCard ec) {
        logTextArea.append("\n** EC-Karte entnehmen **\n");
    }

   
}
